"""Export the generated draft + gap report to a DOCX offer-document draft."""

from pathlib import Path
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

BASE = Path(__file__).parent
EXPORTS = BASE / "exports"
EXPORTS.mkdir(exist_ok=True)


def export_draft(company: dict, sections: dict, gap_report: dict,
                 filename: str = "Drafter_Offer_Document_Draft.docx") -> str:
    doc = Document()

    name = company.get("identity", {}).get("company_name", "The Company")

    title = doc.add_heading(level=0)
    run = title.add_run("DRAFT OFFER DOCUMENT")
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = sub.add_run(f"{name}\n(SME IPO — NSE Emerge / BSE SME)")
    r.bold = True

    note = doc.add_paragraph()
    r = note.add_run(
        "PREPARATORY DRAFT — generated by Drafter for the merchant banker's review. "
        "Not for filing. Regulatory submission is made solely by the authorised "
        "merchant banker after due diligence and certification."
    )
    r.italic = True
    r.font.size = Pt(9)

    # Coverage line
    cov = doc.add_paragraph()
    cov.add_run(
        f"Disclosure coverage: {gap_report['coverage_pct']}%  "
        f"({gap_report['complete_items']}/{gap_report['total_items']} items complete)  |  "
        f"Defects flagged: {len(gap_report['defects'])}"
    ).bold = True

    doc.add_page_break()

    # Sections
    for sec_id in ["S2", "S3", "S4", "S5", "S6"]:
        if sec_id not in sections:
            continue
        sec = sections[sec_id]
        doc.add_heading(sec["title"], level=1)
        maps = ", ".join(sec.get("maps_to", []))
        tag = doc.add_paragraph()
        tr = tag.add_run(f"[Maps to disclosure requirements: {maps}]")
        tr.italic = True
        tr.font.size = Pt(8)
        tr.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
        for para in sec["text"].split("\n"):
            if para.strip():
                doc.add_paragraph(para.strip())

    # Gap report appendix
    doc.add_page_break()
    doc.add_heading("Appendix — Gap & Consistency Report", level=1)

    if gap_report["defects"]:
        doc.add_heading("Defects requiring attention", level=2)
        for d in gap_report["defects"]:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(f"[{d['id']}] {d['detail']}")
            run.font.color.rgb = RGBColor(0xC0, 0x00, 0x00)

    doc.add_heading("Disclosure checklist", level=2)
    table = doc.add_table(rows=1, cols=4)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text = "Item"
    hdr[1].text = "Requirement"
    hdr[2].text = "Source"
    hdr[3].text = "Status"
    for item in gap_report["items"]:
        row = table.add_row().cells
        row[0].text = item["id"]
        row[1].text = item["requirement"]
        row[2].text = item["source"]
        row[3].text = item["status"]

    out_path = EXPORTS / filename
    doc.save(out_path)
    return str(out_path)


if __name__ == "__main__":
    from engine import load_sample_company, run_full
    company = load_sample_company()
    out = run_full(company)
    path = export_draft(company, out["sections"], out["gap_report"])
    print("Saved:", path)
